// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Api.Data;

#nullable disable

namespace StudentManagement.Api.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Api.Models.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RocnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RocnikId");

                    b.ToTable("Predmety");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Rocnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rocniky");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RocnikId")
                        .HasColumnType("int");

                    b.Property<int>("TridaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RocnikId");

                    b.HasIndex("TridaId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Trida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kapacita")
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tridy");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HesloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzivatelskeJmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UzivatelskeJmeno")
                        .IsUnique();

                    b.ToTable("Uzivatele");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Znamka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hodnota")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("UcitelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredmetId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UcitelId");

                    b.ToTable("Znamky");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Predmet", b =>
                {
                    b.HasOne("StudentManagement.Api.Models.Rocnik", "Rocnik")
                        .WithMany()
                        .HasForeignKey("RocnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rocnik");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Student", b =>
                {
                    b.HasOne("StudentManagement.Api.Models.Rocnik", "Rocnik")
                        .WithMany("Studenti")
                        .HasForeignKey("RocnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Api.Models.Trida", "Trida")
                        .WithMany("Studenti")
                        .HasForeignKey("TridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rocnik");

                    b.Navigation("Trida");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Znamka", b =>
                {
                    b.HasOne("StudentManagement.Api.Models.Predmet", "Predmet")
                        .WithMany("Znamky")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Api.Models.Student", "Student")
                        .WithMany("Znamky")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Api.Models.Uzivatel", "Ucitel")
                        .WithMany()
                        .HasForeignKey("UcitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");

                    b.Navigation("Ucitel");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Predmet", b =>
                {
                    b.Navigation("Znamky");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Rocnik", b =>
                {
                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Student", b =>
                {
                    b.Navigation("Znamky");
                });

            modelBuilder.Entity("StudentManagement.Api.Models.Trida", b =>
                {
                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
